# Dependencies
markdown:         kramdown

# Setup
title:            Traceroute the way
description:      Traceroute the way - weblog
tagline:          di Jiang Wu
paginate:         5
paginate_path:    '/page/:num'
baseurl:          '/'
url:              'https://jiangwu.eu'
permalink:        '/:year/:month/:title/'
license:
  link:           'https://github.com/JWuCines/JWuCines.github.io/blob/master/LICENSE.md'
  label:          'MIT License'
author:
  name:           Jiang Wu
  url:            https://jiangwu.eu
  email:          github@jiangwu.eu

# Social media vars
twitter_username:     JWuCines
github_username:      JWuCines
bitbucket_username:   -
linkedin_username:    jwucines
google_plus_username: JiangWuCines
facebook_username:    JWuCines
telegram_username:    JWuCines
disqus_username:      -
fb_app_id:            0

# Custom vars
version:          0.3.0
github:
  repo:           https://github.com/JWuCines/JWuCines.github.io

# Custom configs
gems: [jekyll-paginate]

kramdown:
  auto_ids: true # Auto-generate ID's for headings

theme: jekyll-theme-minimal