# Dependencies
markdown:         kramdown

# Setup
title:            Jiang Wu
description:      Jiang Wu Website
tagline:          Data Engineer @ Adyen (NL)
paginate:         5
paginate_path:    '/blog/page/:num'
url:              'https://www.jiangwu.eu'
permalink:        '/:year/:month/:title/'
license:
  link:           'https://github.com/JWuCines/jwucines.github.io/blob/master/LICENSE.md'
  label:          'MIT License'
author:
  name:           Jiang Wu
  url:            https://www.jiangwu.eu
  email:          github@jiangwu.eu

# Social media vars
twitter_username:     JWuCines
github_username:      JWuCines
bitbucket_username:   JWuCines
linkedin_username:    wuj
facebook_username:    JWuCines
telegram_username:    JWuCines
disqus_username:      JWuCines
fb_app_id:            0

# Custom vars
version:          0.4.0
github:
  repo:           https://github.com/JWuCines/jwucines.github.io

# Custom configs
plugins: [jekyll-paginate]

kramdown:
  auto_ids: true # Auto-generate ID's for headings

theme: jekyll-theme-minimal