# Dependencies
markdown:         kramdown

# Setup
title:            Traceroute the way
description:      Traceroute the way - Manuele Trimarchi's weblog
tagline:          di Manuele Trimarchi
paginate:         5
paginate_path:    '/page/:num'
baseurl:          '/'
url:              'https://trimarchimanuele.it'
permalink:        '/:year/:month/:title/'
license:
  link:           'https://github.com/mtrimarchi/mtrimarchi.github.io/blob/master/LICENSE.md'
  label:          'MIT License'
author:
  name:           Manuele Trimarchi
  url:            https://trimarchimanuele.it
  email:          github@trimarchimanuele.it

# Social media vars
twitter_username:     mtrimarchi
github_username:      mtrimarchi
bitbucket_username:   mtrimarchi
linkedin_username:    trimarchimanuele
google_plus_username: ManueleTrimarchi
facebook_username:    mtrimarchi
telegram_username:    mtrimarchi
disqus_username:      trimarchimanuele
fb_app_id:            254147531706027

# Custom vars
version:          0.3.0
github:
  repo:           https://github.com/mtrimarchi/mtrimarchi.github.io

# Custom configs
gems: [jekyll-paginate]

kramdown:
  auto_ids: true # Auto-generate ID's for headings
